# Generated by Django 4.0.4 on 2022-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
            ],
        ),
    ]
